version: 1.1.{build}
init:
  - git config --global core.autocrlf true
build_script:
  - SET BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
  - build.cmd
artifacts:
  - path: 'artifacts/*.nupkg'
    name: NuGet
clone_depth: 1
test: off
deploy: off